package:
  version: 1.15.20
  url: https://github.com/pooza/ginseng-core
  authors:
    - Tatsuya Koishi
  email:
    - tkoishi@b-shock.co.jp
  description: ginseng core libraries
  license: MIT
environment: development
cert:
  url: https://curl.haxx.se/ca/cacert.pem
error:
  backtrace:
    level: 5
crypt:
  password: mulukhiya
  encoder: base64
http:
  retry:
    limit: 5
    seconds: 1
  timeout:
    seconds: 30
line:
  token: null
  urls:
    api: https://api.line.me
  to: U00
logger:
  mask_fields:
    - password
    - token
    - secret
